name: Bug Report
description: Report a bug or unexpected behavior in RowaKit Table
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I click the sort button, the table...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Create a table with columns...
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The table should sort in ascending order...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: The table throws an error...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Reproducible Example
      description: Please provide a minimal code example that reproduces the issue
      render: typescript
      placeholder: |
        import { RowaKitTable, col } from '@rowakit/table';
        
        const columns = [
          col.text('name'),
          col.text('email'),
        ];
        
        <RowaKitTable fetcher={myFetcher} columns={columns} />
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: RowaKit Version
      description: Which version of @rowakit/table are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: react-version
    attributes:
      label: React Version
      description: Which version of React are you using?
      options:
        - React 18.x
        - React 17.x
        - React 19.x (beta/canary)
        - Other (specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where does this bug occur?
      options:
        - Browser (Chrome/Edge)
        - Browser (Firefox)
        - Browser (Safari)
        - Node.js/SSR
        - Other (specify in additional context)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
        - Browser console errors?
        - Network errors?
        - Does it work in other browsers/environments?
      placeholder: Console shows TypeError...

  - type: checkboxes
    id: checklist
    attributes:
      label: Before Submitting
      options:
        - label: I have searched existing issues to make sure this isn't a duplicate
          required: true
        - label: I have provided a minimal reproducible example
          required: false
        - label: I have checked that this is not a scope violation (virtualization, grouping, pivot, etc.)
          required: true
